{{- if and .Values.ipWhitelist.enabled .Values.ipWhitelist.sourceRange }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.ipWhitelist.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ipAllowList:
    sourceRange:
      {{- range .Values.ipWhitelist.sourceRange }}
      - {{ . }}
      {{- end }}
{{- end }}