apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.logs.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "youtrack.labels" . | nindent 4 }}
  annotations:
    everest.io/disk-volume-type: {{ .Values.persistence.logs.storageType }}
spec:
  {{- $storageClass := include "youtrack.logs.storageClass" . }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
  accessModes: {{ include "youtrack.logs.accessModes" . }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.storageSize }}
