apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hedgedoc.shortName" . }}-db-secret
stringData:
  {{ if .Values.hedgedoc.database }}
  connection: "{{ .Values.hedgedoc.database.type }}://{{ .Values.hedgedoc.database.username }}:{{ .Values.hedgedoc.database.password }}@{{ .Values.hedgedoc.database.host }}:{{ .Values.hedgedoc.database.port }}/{{ .Values.hedgedoc.database.databaseName }}"
  {{ else }}
  connection: "postgres://localhost/hedgedoc"
  {{ end }}