{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-archiver.fullname" . }}-tika
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "open-archiver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tika.replicas }}
  selector:
    matchLabels:
      {{- include "open-archiver.selectorLabelsTika" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open-archiver.selectorLabelsTika" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tika
          securityContext:
            {{- toYaml .Values.tika.securityContext | nindent 12 }}
          image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}"
          imagePullPolicy: {{ .Values.tika.image.pullPolicy }}
          ports:
            - containerPort: 9998
              name: tika
              protocol: TCP
          {{- with .Values.tika.resources }}
          resources:
            {{- if or ((index . "limits" | default dict).cpu | default false) ((index . "limits" | default dict).memory | default false) }}
            limits:
              {{- toYaml .limits | nindent 14 }}
            {{- end }}
            {{- if or ((index . "requests" | default dict).cpu | default false) ((index . "requests" | default dict).memory | default false) }}
            requests:
              {{- toYaml .requests | nindent 14 }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
