apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.data.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "open-archiver.labels" . | nindent 4 }}
spec:
  {{- $storageClass := include "open-archiver.data.storageClass" . }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.storageSize }}
