{{- if .Values.secret.createKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-archiver.fullname" . }}-secret-keys
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  JWT_SECRET: {{ if .Values.secret.jwtSecret }}{{ .Values.secret.jwtSecret }}{{ else }}{{ randAlphaNum 64 }}{{ end }}
  ENCRYPTION_KEY: {{ if .Values.secret.encryptionKey }}{{ .Values.secret.encryptionKey }}{{ else }}{{ randBytes 32 | b64enc | trunc 64 }}{{ end }}
  STORAGE_ENCRYPTION_KEY: {{ if .Values.secret.storageEncryptionKey }}{{ .Values.secret.storageEncryptionKey }}{{ else }}{{ randBytes 32 | printf "%x" }}{{ end }}
  REDIS_PASSWORD: {{ if .Values.secret.redisPassword }}{{ .Values.secret.redisPassword }}{{ else }}{{ randAlphaNum 32 }}{{ end }}
  MEILI_MASTER_KEY: {{ if .Values.secret.meiliMasterKey }}{{ .Values.secret.meiliMasterKey }}{{ else }}{{ randAlphaNum 32 }}{{ end }}
{{- end }}
