{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-archiver.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.config.storageS3AccessKeyId }}
  STORAGE_S3_ACCESS_KEY_ID: {{ .Values.config.storageS3AccessKeyId | quote }}
  {{- end }}
  {{- if .Values.config.storageS3SecretAccessKey }}
  STORAGE_S3_SECRET_ACCESS_KEY: {{ .Values.config.storageS3SecretAccessKey | quote }}
  {{- end }}
{{- end }}
