{{- $createForDbUrl := and .Values.maxmind.dbUrl (not .Values.maxmind.existingSecret) -}}
{{- $createForGeoip := and .Values.geoipupdate.enabled (not .Values.geoipupdate.existingSecret) -}}
{{- if or $createForDbUrl $createForGeoip }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maxmind-geoip-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maxmind-geoip-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $createForDbUrl }}
  MAXMIND_DB_URL: {{ .Values.maxmind.dbUrl | quote }}
  {{- end }}
  {{- if $createForGeoip }}
  GeoIP.conf: |
    AccountID {{ .Values.geoipupdate.accountId }}
    LicenseKey {{ .Values.geoipupdate.licenseKey }}
    EditionIDs {{ .Values.geoipupdate.editionId }}
  {{- end }}
{{- end }}
